### PR TITLE
Refactor feature time series.

### PR DESCRIPTION
**Pull request by dangom**
I noticed that the computation of the feature time series was a bit of a bottleneck of AROMA.
I've refactored the code for a >300x speedup, i.e., from over 50min to less than 10s in an example with 350 components and 1000 timepoints.

I should note there is 1 slight difference from my code to the original. I use `np.roll` to generate the shifted realignment parameters. That, by design, does not set the edges to 0, as in the original code. I didn't see this as a relevant issue since the difference in feature estimates is minimal ( <0.01% on avg -- <0.3% on max), as seen in the figure below:

old_vs_new

### CODE REVIEW

**Comment by dangom** [comment]
Although I've just seen that another PR already did this. =)

**Comment by maartenmennes** [comment]
Hi Daniel,
which PR are you referring to? The big one by Rob?
Maarten

**Comment by dangom** [comment]
Hi Maarten,

this one: #8 . I guess it's probably the big one you mean

**Comment by maartenmennes** [comment]
This is addressed in the 0.4.4-beta release. Many thanks for the suggestion Daniel, this indeed results in a massive speed-up!

**Pull request closed without merging**
